main: com.hektropolis.houses.Houses
name: Houses
version: 1.6.4.1
author: Solivero
description: Houses
depend: [Vault]
commands:
  house:
    description: Commands for Houses
    aliases: [houses, h]
