#===================================
#=    AlphaCTX's Houses plugin     =
#===================================
# 
#
#================================
#=     MAX OWNED PROPERTIES     =
#================================
max-houses-per-player: 3

#============================
#=     STOREAGE OPTIONS     =
#============================
database:
  use-mysql: false
  host: localhost
  port: 3306
  user: root
  pass: password
  database: houses
  sqlite-file: houses.db
  save-interval: 60 # seconds
  debug: false

#=============================
#=     TELEPORT SETTINGS     =
#=============================
teleport-wait: 5
rent:
  period: 2400 # seconds (2 Minecraft days)
  check-interval: 600 # seconds

cleanup:
  check-interval: 86400 # seconds
  inactive-days: 30

#===========================
#=     CUSTOM MESSAGES     =
#===========================
messages:
  buy-success: "&aPurchased house {id}"
  sell-success: "&aSold house {id}"
  rent-success: "&aRented house {id}"
  stop-rent-success: "&aStopped renting house {id}"
  door-locked: "&cYou don't own this house"
  rent-paid: "&aRent for house {id} paid"
  rent-stopped: "&cRent unpaid, house {id} lost"
  inactive-removed: "&cHouse {id} removed due to inactivity"
