max-houses-per-player: 3
database:
  use-mysql: false
  host: localhost
  port: 3306
  user: root
  pass: password
  database: houses
  save-interval: 10 # seconds
  debug: false

teleport-wait: 5
rent:
  period: 86400 # seconds
  check-interval: 600 # seconds

messages:
  buy-success: "&aPurchased house {id}"
  sell-success: "&aSold house {id}"
  rent-success: "&aRented house {id}"
  stop-rent-success: "&aStopped renting house {id}"
  door-locked: "&cYou don't own this house"
