#===================================
#=    AlphaCTX's Houses plugin     =
#===================================
# 
#
#================================
#=     MAX OWNED PROPERTIES     =
#================================
max-houses-per-player: 3

#============================
#=     STOREAGE OPTIONS     =
#============================
database:
  use-mysql: false
  host: localhost
  port: 3306
  user: root
  pass: password
  database: houses
  sqlite-file: houses.db
  save-interval: 60 # seconds
  debug: false

#=============================
#=     TELEPORT SETTINGS     =
#=============================
teleport-wait: 5
rent:
  period: 86400 # seconds
  check-interval: 600 # seconds

#===========================
#=     CUSTOM MESSAGES     =
#===========================
messages:
  buy-success: "&aPurchased house {id}"
  sell-success: "&aSold house {id}"
  rent-success: "&aRented house {id}"
  stop-rent-success: "&aStopped renting house {id}"
  door-locked: "&cYou don't own this house"
