name: MinecraftHouses
version: 1.2.1
main: com.alphactx.MinecraftHouses
api-version: 1.16
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  houses:
    description: House commands
    permission: mchouses.use
    aliases: [house]
    tab-completer: com.alphactx.HousesCommand
permissions:
  mchouses.use:
    default: true
  houses.use:
    default: true
  houses.admin:
    default: op
